version: '3'

networks:
  default:
    external:
      name: inner

services:

  db:
    image: postgres:12
    container_name: db
    ports:
    - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'

  backend:
    build:
      context: ../src/coffee_juice
      dockerfile: ./Dockerfile
    container_name: coffee_cup_orange_juice_glass
    restart: always
    depends_on:
      - db
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=5
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=1
    command: sh -c "/wait && /entrypoint.sh"


  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  redis:
    image: redis
    ports:
      - '6379:6379'