"""Change telegram

Revision ID: 014d60fdf395
Revises: 46b91ba463a9
Create Date: 2021-10-29 01:04:16.595554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014d60fdf395'
down_revision = '46b91ba463a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_number', sa.String(), nullable=False, comment='Почта пользователя'))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Почта пользователя'))
    op.drop_column('users', 'telegram_number')
    # ### end Alembic commands ###
