"""First migration

Revision ID: 46b91ba463a9
Revises: 
Create Date: 2021-10-24 22:59:29.060018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46b91ba463a9'
down_revision = None
branch_labels = None
depends_on = None

drink_type = postgresql.ENUM('coffee', 'juice', 'water', 'other', name='drinktype')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID, nullable=False, comment='Идентификатор'),
    sa.Column('nickname', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('email', sa.String(), nullable=False, comment='Почта пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('drinks',
    sa.Column('id', postgresql.UUID, nullable=False, comment='Идентификатор'),
    sa.Column('user_id', postgresql.UUID(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('drink_type', drink_type, nullable=False, comment='Тип напитка'),
    sa.Column('volume', sa.DECIMAL(), nullable=True, comment='Объём напитка'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drinks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drinks')
    op.drop_table('users')
    # ### end Alembic commands ###

    drink_type.drop(op.get_bind())
